name: tnc-discordgang

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL:-https://api-lacripta.legm03.xyz/api/v1}
        NEXT_PUBLIC_DISCORD_CLIENT_ID: ${NEXT_PUBLIC_DISCORD_CLIENT_ID:-}
        NEXT_PUBLIC_DISCORD_GUILD_ID: ${NEXT_PUBLIC_DISCORD_GUILD_ID:-}
    container_name: tnc-frontend
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - '5173:5173'
    networks:
      - tnc-network
      - cloudflare_tunnel

networks:
  tnc-network:
    external: true
  cloudflare_tunnel:
    external: true
