services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tnc-frontend
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - '5173:5173'
    networks:
      - tnc-network
      - cloudflare_tunnel

networks:
  tnc-network:
    external: true
  cloudflare_tunnel:
    external: true
